-- Adjusts experience factor
NDefines.NMilitary.MAX_ARMY_EXPERIENCE = 10000
NDefines.NMilitary.FIELD_EXPERIENCE_SCALE = 0.3
NDefines.NMilitary.FIELD_EXPERIENCE_MAX_PER_DAY = 5000	


--Combat AI
NDefines.NAI.MAX_MICRO_ATTACKS_PER_ORDER = 0
NDefines.NAI.ORG_UNIT_WEAK = 0.70
NDefines.NAI.STR_UNIT_WEAK = 0.70
NDefines.NAI.ORG_UNIT_NORMAL = 0.90
NDefines.NAI.STR_UNIT_NORMAL = 0.80
NDefines.NAI.ORG_UNIT_STRONG = 0.95						
NDefines.NAI.STR_UNIT_STRONG = 0.90

